language: python
python:
- 2.7
- 3.5
- 3.6
install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
- source activate test-environment
- pip install -r requirements.txt
- python setup.py install
script:
- make test
deploy:
  provider: pypi
  user: gmauro
  password:
    secure: FbhOd9wtRniVg+sm9nruITPwzTCk0qmOGamYgs0p9+QKOmc6OeXeTPupj0W9TWC5wUOGf5t3cV+lBM2zlvBKP1m6ZubIpsjZO7M5PU/zs6eompopYpldowBJcOM0DQWAcIsKfNdGwMbFHXwluR9a1I6GuMKjrEbhd7quOa3vuob4jL4+lwFhDAIfbmXza9z/u9OMV2Al870qPAhA1qbhc3AqAYI+T2J5sYAKn1p9KraJWTJpput3XZu81vf2N+X7T5X6P/TPcz8KKunuLWZf6DHJSy0eTUMtYCeOiQ4cRDiY00J0HyHqLvkOB+fZovQRpHLenQuvq6zMliNBtz4mxk5THS7Ni9VjjGoaufEKKcsYDobb0xcw6/PI0yyw3Q+0O9auZTCLOP/UJiYFeZsgy1pVP4oJSr887xON2Dxsu9vjhqHswHqT5LtjT7dSWIZFFuCveEvHzcDLMZuk7nYmBKCNrm4kaEYqyc2mJbX6XWhDVf/B7NFBfWIvbnvZxwdNP8aeW++TOCiF7RPZf5heMX0AZDKiDOghQmQoCgVDJTUvTkUSDZcOK9/6jwXupZZb8zAe1+9adJ47eUHWAoFVtvsW510DY41HyF1MvA02443ccV/MYUEiLBUK74qn0uVlv9WAktip+u2aCmRfqttJ5NWeF7tDYni1Q41ujtsCXAE=
  on:
    tags: true
distributions: bdist_wheel
