language: python
python:
- 2.7
- 3.5
- 3.6
install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
- source activate test-environment
- pip install -r requirements.txt
- python setup.py install
script:
- make test
deploy:
  provider: pypi
  user: gmauro
  password:
    secure: j2XhBD7Z+vcrP+jletr1jKtdsISQ5l1LpIJAmDURIwEHVrejX/DTrB1eFhdRGqHSSpP40Xhliw9k7E1NCiyGmO/x/2SApZ1Lzos+LU1Qg6TDFZZDct89ViysOh5sfRoJB/oApAeT9s8ow02D025Dw0kcefNWK3XjvTaj+4wJWn7G327zM+s/on6ai4XfgeFo76A1SOGs1JNaZqNmnOKH6i4UcH/WXxJr5tFTAHh1Qns0/OEw9dvdh58+EpMxNkrecz6yBDF/Ml7qTCWR8iE6cf02rAQ6JCDOT4slrxI7v9GERaIvxZSEMV9+bAMj+2kFhy7E8rFT7856oOVUQHpWMFsCyyuBL+vQPuZxrS2WwhKlBN2rPEGFHimawmRDynh3gcUBakHpstf+QQ7HoFY6uWa/Rv3gGgScJTF0SzU/i+fQk8eJGO6Mn0uBJxghUTosk/8FTirF5BvOgya8ePYUE1CW0faikIP5sa1JsmrqaL2kh3ut8d7SOdK3TJmsMSy3pEUYNx71OeSG2v2pqFsVxadWcpquH1eyDfxwaJxO8K4KpDIJLPyS3Wz1sQsoYKiBWhqrUM3MlcwNBf0RknwrEzbA1U2NcfI0sflm3C82QZf8GbtBLVYSJ+LyJvxIHsFug7lypGyZD9isClqnzxsowbBVQkKcEh2rMyzvKkIhaf4=
  on:
    tags: true
    distributions: bdist_wheel
    repo: gmauro/comoda
