language: python
python:
- 2.7
- 3.5
- 3.6
install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
- source activate test-environment
- pip install -r requirements.txt
- python setup.py install
script:
- make test
deploy:
  provider: pypi
  user: gmauro
  password:
    secure: LGhPhiwdzjCSt2hwgDTiAy85AjOW2tk0GFLHPp+VMDDBK3v/Sb9HInOLDDyuvSu3kBUUkn7ms29NqDoZEFblLnoxhdffcydEFVfl/GD683uS6oj5UnuIzgkr6o9HygHYxbmSD5a6/J+XbGG7moj5zbOc0afpGUKjaDsf1/BxfXxI78djfKPr3SRzQUCeMXOZOikdG019AJWq6X/O2HLvjTn7xzeDzqD0jyG4azCsLgdPulJ7/xBxA+r7l0DklaBZgl3Q2dfRNM149d8g4w0Nuy9CBZGYzqX01mvG86nNb2IvZX+M6hyMxQfnaxtu/YpkwzFnZw2IUxinlHe+FARP5pD6132GRINE1CRPHHKukG6CJZaMeH7jZeSFiaGvg/MQWWv+LHRhBuTCf/+pLD+1n8f0jnDBpuyw7KAZIPGQIbu2i/iG5CcR0rvAoRVzQO9Q5oM57xUYBqLlt8iAZ/2Xp6haoys7nHu7v1ZYnHXouBCtrgmSKxkQYX+iDyBnEIsonvNhw5+bI57pfc5ZL1WIPaFvPKKmC2pYLdsF9JVGgjgAFmDP1NuLdLUCAMaNQZdtnXNe0nUIjlKu6lxDSpKVgHqgDHz88sJ580+Ef8f1oEEUDqSRqRMyBXeOrQ1xE1acXXZUQ2uQCxO8RNumW9UDDq7Sgn2UqrOim1gHQlWmqZo=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: gmauro/comoda
