language: python
python:
- 2.7
- 3.5
- 3.6
install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
- source activate test-environment
- pip install -r requirements.txt
- python setup.py install
script:
- make test
deploy:
  provider: pypi
  user: gmauro
  password:
    secure: TuqYug/VWaDdTTDtCym80pOQ+H5pMBPT3Tbr1gAUUiCwvcVlNLB0c5NhHdwcKK1HulSQ81rddK2MPpzo0JAXM2qFfuFj6sO13rwH9OozmVPYifB5jE1qF1uv5vGG+HfubTm0WFrHDgupv1okm656pBy0uJH5lSoNnS0p9SduiQPIWYm0+Q1zjO5gW4T+MOgMU3AmqYUvClMWozzKMZtWQ2N3lAWPiuWRttikZNeCLzhsHtcrWbtHBeBEAaTCbVWTPRu4q+tVFwX/HsotcnZ66jITFWJgwJUL093ZHrFjJ3sHqrRycQE0FdY8HPV/dJCXAYjIziGRQA2TE/ifbD/jtRNPTmAcrZG/wW3cN7sz1W/YVSt73M4RWJ/jfcP7RGpblsCMgPoY3/raMhoonlnKbVqCAnMTEdzZZu0bymGh+It7LEoSHeCi9zBT4NwRgZaUhzwKiK7Xa069kttJy+u+x4SgWRHDdFaXlt60qngq+VQpG94KRz35yoahNKOJNRGHY05gWVgD6j4XkDnCfojHFTxBc8dgXZZwgwFg2VW2qivMUehJvtHlD5wSz8DdHdEWnPwO+86Iz+yduNVwmR2dv4JA0JsMYElskd2i1NSksIGMLstYPC7445adU+7xcZU8ylpgACT/NSHibF3l0xqL+enZjFJfXvrJ0jgsTKc+4Ao=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: gmauro/comoda
